### ISSUE TITLE
Will you please upload Trained model? 

### ISSUE THREAD

**Issue by anilbatra2185** [ShiningLab/POS-Tagger-for-Punctuation-Restoration#1]
Hi @MrShininnnnn

Thanks for your interesting work. I am wondering if you can upload the trained model which can be used for inference or evaluation only.

Thanks

**Comment by MrShininnnnn** [comment]
Hi @anilbatra2185 

Thanks for asking. The inference version is on my to-do list. Will be published soon.

**Comment by anilbatra2185** [comment]
Thanks @MrShininnnnn for your response.

Thanks

**Comment by MrShininnnnn** [comment]
A demo has been upload, so the issue is closed.
